services:
  - type: web
    name: jobfit
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: LLM_NAME
        value: your-llm-name:type
      - key: OPENAI_API_KEY
        sync: false # Set this in Render dashboard as a secret
    healthCheckPath: /
